POST http://localhost:3000/login

//User
GET http://localhost:3000/users
//Authorization: Bearer token
###
POST http://localhost:3000/users
Content-Type: application/json
{
  "lastname": "Chaksoukane",
  "firstname": "Mickael",
  "email": "mickael@test.com",
  "password": "test"
}
### 
GET http://localhost:3000/users/1
###
PUT http://localhost:3000/users/1
Content-Type: application/json
//Authorization: Bearer token
{
  "role": "ADMIN"
}
### 
DELETE http://localhost:3000/users/1




//Employee
GET http://localhost:3000/employee
###
POST http://localhost:3000/employee
Content-Type: application/json
{
 
### 
GET http://localhost:3000/employee/1
###
PUT http://localhost:3000/employee/1
Content-Type: application/json
### 
DELETE http://localhost:3000/employee/1
 
//Task
GET http://localhost:3000/task
###
POST http://localhost:3000/task
Content-Type: application/json
### 
GET http://localhost:3000/task/1
###
PUT http://localhost:3000/task/1
Content-Type: application/json
### 
DELETE http://localhost:3000/task/1



//Project
GET http://localhost:3000/project
###
POST http://localhost:3000/project
Content-Type: application/json
### 
GET http://localhost:3000/project/1
###
PUT http://localhost:3000/project/1
Content-Type: application/json
### 
DELETE http://localhost:3000/project/1

